/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package des;

import java.io.File;
import java.io.IOException;
import java.nio.file.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author nisit
 */
public class Interfaz1 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(Interfaz1.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Ruta = new javax.swing.JTextField();
        Btn_Buscar = new javax.swing.JButton();
        Btn_Descifrar = new javax.swing.JButton();
        Btn_Cifrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_Estado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Btn_Leer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("🔐 Cifrado y Descifrado con DES");

        Btn_Buscar.setText("📁 Buscar archivo");
        Btn_Buscar.setFocusPainted(false);
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });

        Btn_Descifrar.setText("🔓 Descifrar");
        Btn_Descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DescifrarActionPerformed(evt);
            }
        });

        Btn_Cifrar.setText("🔒 Cifrar");
        Btn_Cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CifrarActionPerformed(evt);
            }
        });

        Txt_Estado.setColumns(20);
        Txt_Estado.setRows(5);
        jScrollPane1.setViewportView(Txt_Estado);

        jLabel1.setText("Estado del Proceso:");

        Btn_Leer.setText("📄 Ver contenido");
        Btn_Leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LeerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Cifrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Descifrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Leer)
                        .addContainerGap(221, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_Ruta)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Buscar))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cifrar)
                    .addComponent(Btn_Descifrar)
                    .addComponent(Btn_Leer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            Txt_Ruta.setText(archivo.getAbsolutePath());
            mostrarMensaje("📂 Archivo seleccionado: " + archivo.getName());
        }
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_CifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CifrarActionPerformed
        try {
            Metodos.Cifrar(Txt_Ruta.getText(), this);
        } catch (Exception ex) {
            mostrarMensaje("❌ Error al cifrar: " + ex.getMessage());
            Logger.getLogger(Interfaz1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_CifrarActionPerformed

    private void Btn_DescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DescifrarActionPerformed
        
        try {
            Metodos.descifrar(Txt_Ruta.getText(), this);
        } catch (Exception ex) {
            mostrarMensaje("❌ Error al descifrar: " + ex.getMessage());
            Logger.getLogger(Interfaz1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_DescifrarActionPerformed

    private void Btn_LeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LeerActionPerformed
        try {
            mostrarContenidoArchivo(Txt_Ruta.getText());
        } catch (Exception e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_Btn_LeerActionPerformed

    private void mostrarContenidoArchivo(String ruta) throws IOException {
        
        if (ruta == null || ruta.isEmpty()) {
            mostrarMensaje("⚠️ Por favor selecciona un archivo.");
            return;
        }

        File archivo = new File(ruta);
        if (!archivo.exists()) {
            mostrarMensaje("⚠️ El archivo no existe.");
            return;
        }

        // Crear y mostrar el diálogo
        new Dialog_Leer(this, ruta).setVisible(true);
    
    }

    public void mostrarMensaje(String mensaje) {
        Txt_Estado.append(mensaje + "\n");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Cifrar;
    private javax.swing.JButton Btn_Descifrar;
    private javax.swing.JButton Btn_Leer;
    private javax.swing.JTextArea Txt_Estado;
    private javax.swing.JTextField Txt_Ruta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
